spring.application.name=university-management-system
server.port=8081
spring.datasource.url=jdbc:postgresql://localhost:5432/ums_dev
spring.datasource.username=ums_user
spring.datasource.password=ums_pass
spring.jpa.open-in-view=false
